name: Linux C++ CI

on:
  workflow_dispatch:
  push:

jobs:
  x86_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prerequisites
      run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+
    - name: make
      run: make
    - name: test
      run: ./test_stxtyper.sh
    - name: Upload artifacts on failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }} # only run if the job fails
      with: 
        name: stxtyper-failed-test-linux
        path: |
            ./*
            test/* 
        retention-days: 14
        
  arm_linux:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: prerequisites
      run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+
    - name: make
      run: make
    - name: test
      run: ./test_stxtyper.sh
    - name: Upload artifacts on failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }} # only run if the job fails
      with: 
        name: stxtyper-failed-test-linux
        path: |
            ./*
            test/* 
        retention-days: 14
